# Generated by Django 2.2.7 on 2019-12-20 19:51

from django.db import migrations, models
import django.db.models.deletion
import pretix.base.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0141_seat_sorting_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=190, unique=True)),
                ('status', models.CharField(db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Event')),
                ('waiting_list_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pretixbase.WaitingListEntry')),
            ],
            options={
                'ordering': ['created_at', 'status'],
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name='TicketRequestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pretixbase.Question')),
                ('ticket_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pretix_ticket_request.TicketRequest')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
    ]
