# Generated by Django 2.2.7 on 2019-12-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_ticket_request', '0002_auto_20191220_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketrequest',
            name='waiting_list_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pretixbase.WaitingListEntry'),
        ),
    ]
