# Generated by Django 2.2.7 on 2019-12-21 04:34

from django.db import migrations
import jsonfallback.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_ticket_request', '0003_auto_20191220_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrequest',
            name='data',
            field=jsonfallback.fields.FallbackJSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='TicketRequestAnswer',
        ),
    ]
