# Generated by Django 2.2.7 on 2019-12-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_ticket_request', '0004_auto_20191221_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrequest',
            name='name',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
