# Generated by Django 2.2.7 on 2019-12-24 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0141_seat_sorting_rank'),
        ('pretix_ticket_request', '0005_ticketrequest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketrequest',
            name='waiting_list_entry',
        ),
        migrations.AddField(
            model_name='ticketrequest',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_request', to='pretixbase.Voucher'),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_requests', to='pretixbase.Event'),
        ),
    ]
