# Generated by Django 2.2.7 on 2020-01-21 00:30

from django.db import migrations, models
import django.db.models.deletion
import jsonfallback.fields
import pretix.base.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0141_seat_sorting_rank'),
        ('pretix_ticket_request', '0006_auto_20191224_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('email', models.EmailField(db_index=True, max_length=190, unique=True)),
                ('profile', jsonfallback.fields.FallbackJSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='pretixbase.Event')),
            ],
            options={
                'ordering': ['created_at'],
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
    ]
